name: Build Docker image

on:
  push:
    paths:
      - Dockerfile
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup QEMU user-mode emulation
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Prepare image tag (master, on schedule)
        if: github.ref == 'refs/heads/master' || github.event_name == 'schedule'
        run: echo "DOCKER_TAG=latest" >> $GITHUB_ENV
      - name: Prepare image tag (other branches)
        if: github.ref != 'refs/heads/master'
        run: echo "DOCKER_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/starrybluesky/venv:${{ env.DOCKER_TAG }}
          cache-from: ghcr.io/starrybluesky/venv:${{ env.DOCKER_TAG }}
